apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu
  name: dev
spec:
   containers:
  - image: singharunk/dev:driver
    name: dev
    env:
    - name: AZURE_STORAGE_ACCOUNT
      value: "xxxxxx"
    - name: AZURE_STORAGE_ACCESS_KEY
      value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    - name: AZURE_MOUNT_POINT
      value: "/opt/container"
    - name: AZURE_STORAGE_ACCOUNT_CONTAINER
      value: "test"
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir ${AZURE_MOUNT_POINT} /tmp/${AZURE_STORAGE_ACCOUNT} && blobfuse ${AZURE_MOUNT_POINT} --container-name=${AZURE_STORAGE_ACCOUNT_CONTAINER} --tmp-path=/tmp/${AZURE_STORAGE_ACCOUNT} -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
