apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu
  name: dev
spec:
   containers:
  - image: singharunk/dev:driver
    name: dev
    env:
    - name: AZURE_STORAGE_ACCOUNT
      value: "xxxxxx"
    - name: AZURE_STORAGE_ACCESS_KEY
      value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    - name: BLOB_CONTAINER
      value: "test"
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir /opt/container /opt/tmp && blobfuse /opt/container --container-name=$BLOB_CONTAINER --tmp-path=/opt/tmp -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120"]
    volumeMounts:
    - name: azure
      mountPath: /opt/share
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: azure
    emptyDir: {}
