apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: custom-role
  namespace: mynamespace
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - pods
  - endpoints
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  - daemonsets
  - deployments
  - controllerrevisions
  - statefulsets
  verbs:
  - '*'
  
  ---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-rolebinding
  namespace: mynamespace
subjects:
- kind: User
  name: custom-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: custom-role
  apiGroup: rbac.authorization.k8s.io
