apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana-config
  namespace: default
data:
  kibana.yml: |
    elasticsearch.hosts: ["http://tst-elasticsearch.default.svc.cluster.local:9200"]
    elasticsearch.ssl.verificationMode: none
    #elasticsearch.username: admin
    #elasticsearch.password: admin
    xpack.security.enabled: "false"
    xpack.monitoring.enabled: "false"
    xpack.apm.enabled: "false"
    xpack.apm.ui.enabled: "false"
    xpack.graph.enabled: "false"
    xpack.grokdebugger.enabled: "false"
    xpack.ml.enabled: "false"
    xpack.reporting.enabled: "false"
    xpack.searchprofiler.enabled: "false"
    xpack.xpack_main.telemetry.enabled: "false"
    xpack.monitoring.kibana.collection.enabled: "false"
    xpack.spaces.enabled: "false"
    xpack.infra.enabled: false
    xpack.canvas.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "cdscscr42hx7qhnxgbxj2892jn3n3n343fvc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tst-kibana
      cluster: npd
      env: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tst-kibana
        cluster: npd
        env: dev
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          value: http://tst-elasticsearch.default.svc.cluster.local:9200
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: ELASTICSEARCH_USERNAME
          value: admin
        - name: ELASTICSEARCH_PASSWORD
          value: admin
        - name: KIBANA_ENCRYPTION_KEY
          value: 786yxv181hxbxqh2178818bxxsaxkxjGbxsmxUyb39
        image: singharunk/kibana:7.10.2-plugin
        imagePullPolicy: Always
        name: kibana
        ports:
        - containerPort: 5601
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: kibanaconfig
          subPath: kibana.yml
      volumes:
      - configMap:
          name: tst-kibana-config
        name: kibanaconfig
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana
  namespace: default
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: tst-kibana
    cluster: npd
    env: dev
  type: ClusterIP
