# certificate for kibana
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana-certificate-pem
  namespace: custom-namespace
data:
  kibana-certificate.pem: <base64>
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana-config
  namespace: custom-namespace
data:
  kibana.yml: |
    server.ssl:
      enabled: true
      key: /usr/share/kibana/config/certs/kibana-certificate.pem
      certificate: /usr/share/kibana/config/certs/kibana-certificate.pem
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    elasticsearch.ssl:
      certificateAuthorities: /usr/share/kibana/config/certs/kibana-certificate.pem
      verificationMode: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana
  namespace: custom-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tst-kibana
      cluster: npd
      env: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tst-kibana
        cluster: npd
        env: dev
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          value: https://tst-elasticsearch.custom-namespace.svc.cluster.local:9200
        - name: SERVER_HOST
          value: 0.0.0.0
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: tst-elasticsearch-user
        - name: KIBANA_ENCRYPTION_KEY
          value: 786yxv181hxbxqh2178818bxxsaxkxjGbxsmxUyb39
        image: kibana:7.11.1
        imagePullPolicy: Always
        name: kibana
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /usr/share/kibana/config/certs
          name: kibana-certificate-pem
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: kibanaconfig
          subPath: kibana.yml
      volumes:
      - name: kibana-certificate-pem
        secret:
          secretName: tst-kibana-certificate-pem
      - configMap:
          name: tst-kibana-config
        name: kibanaconfig
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tst-kibana
    cluster: npd
    env: dev
  name: tst-kibana
  namespace: custom-namespace
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: tst-kibana
    cluster: npd
    env: dev
  type: ClusterIP
---
